### ISSUE TITLE
When upgrading to EnterpriseLibrary.Common.NetCore from 6.0.1312 to 6.3.0, invalid operation occurs:   Message=The connection string for the database 'CMFMasterSystem' does not exist or does not have a valid provider.

### ISSUE THREAD

**Issue by jonathanpickard** [EnterpriseLibrary/data-access-application-block#10] opened 2020-05-05 14:46 UTC
When updating Visual Studio project to .NET Core 3.1 and consequently updating EnterpriseLibrary.Common.NetCore and ExceptionHandling and Logging.Database and Logging I now get a runtime error:

System.InvalidOperationException
  HResult=0x80131509
  Message=The connection string for the database 'CMFMasterSystem' does not exist or does not have a valid provider.
  Source=Microsoft.Practices.EnterpriseLibrary.Data

The connection string hasn't changed.  It is as follows:

    <add name="CMFMasterSystem" connectionString="Data Source=.\PASYS2017;Initial Catalog=PA_OLTP_SYSTEM;Integrated Security=True" providerName="System.Data.SqlClient"/>

Why is the error occurring?
Thanks,
Jonathan.

**Comment by Chavoshi** [comment] 2020-05-08 15:45
Fixed in EnterpriseLibrary.Data.NetCore, v6.3.1.

**Comment by jonathanpickard** [comment] 2020-05-11 08:49
Hi,

Thank you for coming back to me quickly with a response.  I've updated to v6.3.1 in the main startup project for the API I'm developing, however I get the same runtime error.  Have I got all the requisite packages installed together?  See attached files.
![JPickard runtime exception details 1](https://user-images.githubusercontent.com/40670641/81542501-a60f6800-936c-11ea-9f9b-4a19b0565bba.jpg)
![JPickard runtime exception details 2](https://user-images.githubusercontent.com/40670641/81542507-a90a5880-936c-11ea-99c1-4f0fe2493148.jpg)
![JPickard runtime exception details 3](https://user-images.githubusercontent.com/40670641/81542516-ab6cb280-936c-11ea-821b-33c6f5711740.jpg)

**Comment by moein-shafiei** [comment] 2020-05-11 10:39
Hi,
Can you send your logging configuration part. I cannot reproduce the issue. @jonathanpickard

**Comment by jonathanpickard** [comment] 2020-05-11 11:51
Hi, here is the logging configuration XML from the config file:

  <loggingConfiguration name="Logging Application Block"
            tracingEnabled="true"
            defaultCategory="General"
            logWarningsWhenNoCategoriesMatch="true">
    <listeners>
      
      <add name="Database Trace Listener"
					   type="Microsoft.Practices.EnterpriseLibrary.Logging.Database.FormattedDatabaseTraceListener, Microsoft.Practices.EnterpriseLibrary.Logging.Database, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null"
					   listenerDataType="Microsoft.Practices.EnterpriseLibrary.Logging.Database.Configuration.FormattedDatabaseTraceListenerData, Microsoft.Practices.EnterpriseLibrary.Logging.Database, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null"
					   databaseInstanceName="CMFMasterSystem"
					   writeLogStoredProcName="PA_SP_INSERTPAYROLLERRORLOG"
					   addCategoryStoredProcName="PA_SP_ADDCATEGORY"
					   formatter="DataBase Formatter" />

      
      <add name="Rolling Flat File Trace Listener" type="Microsoft.Practices.EnterpriseLibrary.Logging.TraceListeners.RollingFlatFileTraceListener, Microsoft.Practices.EnterpriseLibrary.Logging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null"
           listenerDataType="Microsoft.Practices.EnterpriseLibrary.Logging.Configuration.RollingFlatFileTraceListenerData, Microsoft.Practices.EnterpriseLibrary.Logging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null"
           fileName="RollingFlatFile.log"
           footer="----------------------------------" formatter="Text Formatter"
           header="" rollInterval="Day"
           traceOutputOptions="DateTime, Timestamp" filter="All" />
    </listeners>
    <formatters>
      <add type="Microsoft.Practices.EnterpriseLibrary.Logging.Formatters.TextFormatter, Microsoft.Practices.EnterpriseLibrary.Logging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null"
				   template="Timestamp: {timestamp}{newline}&#xA;Message: {message}{newline}&#xA;Category: {category}{newline}&#xA;Priority: {priority}{newline}&#xA;EventId: {eventid}{newline}&#xA;Severity: {severity}{newline}&#xA;Title:{title}{newline}&#xA;Machine: {localMachine}{newline}&#xA;App Domain: {localAppDomain}{newline}&#xA;ProcessId: {localProcessId}{newline}&#xA;Process Name: {localProcessName}{newline}&#xA;Thread Name: {threadName}{newline}&#xA;Win32 ThreadId:{win32ThreadId}{newline}&#xA;Extended Properties: {dictionary({key} - {value}{newline})}"
				   name="Text Formatter" />

      <add type="Microsoft.Practices.EnterpriseLibrary.Logging.Formatters.TextFormatter, Microsoft.Practices.EnterpriseLibrary.Logging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null"
				   template="Extended Properties: {dictionary({key} !@# {value}&#xA;&#xA;)}"
				   name="DataBase Formatter" />
    </formatters>
    <categorySources>
      <add switchValue="All" name="General">
        <listeners>
          <add name="Database Trace Listener" />
        </listeners>
      </add>

      <add switchValue="All" name="Database Category">
        <listeners>
          <add name="Database Trace Listener" />

          
          
        </listeners>
      </add>
    </categorySources>
    <specialSources>
      <allEvents switchValue="All" name="All Events" />
      <notProcessed switchValue="All" name="Unprocessed Category" />
      <errors switchValue="All" name="Logging Errors &amp; Warnings">
        <listeners>
          <add name="Database Trace Listener" />
        </listeners>
      </errors>
    </specialSources>
  </loggingConfiguration>

**Comment by moein-shafiei** [comment] 2020-05-13 09:27
This issue is fixed in 
EnterpriseLibrary.Data.NetCore v6.3.2 and 
EnterpriseLibrary.Logging v6.3.2 and 
EnterpriseLibrary.Logging.NetCore v6.3.2

**Comment by jonathanpickard** [comment] 2020-05-13 09:36
Fantastic!  I can confirm the issue has been fixed in my application.  Thank you for spending time fixing the issue.

**Closed** 2020-05-13 09:38 UTC
